# Generated by Django 5.2.11 on 2026-02-21 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['game'], name='scores_scor_game_9b30f9_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user'], name='scores_scor_user_id_bcceec_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['date'], name='scores_scor_date_a43bff_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user', 'game'], name='scores_scor_user_id_1e66f1_idx'),
        ),
    ]
